# set condition for when to run the action files 
on: 
  push: 
    branches: ["master"]
# build docker image , push dockerhub
env: 
  DOCKER_IMAGE_NAME: reactjs-itp-gen1
  HELM_REPO: seang454/reacjs-helm-gitops
  GITOPS_REPO: reactjs-helm
jobs:
    # ✅ Run SonarQube FIRST
  sonar-job:
    uses: ./.github/workflows/sonar-analysis.yml
    secrets:
      SONAR_API_TOKEN: ${{ secrets.SONAR_API_TOKEN }}  
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}


  ci-job: 
    needs: sonar-job
    runs-on: ubuntu-latest 
    environment: DOCKER_ENV
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3
      - name: Using Commit SHA 
        run: |
          echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
# GITHUB_SHA : This variable contains the full commit SHA hash that triggered the workflow.
# ${GITHUB_SHA::8} : This is Bash substring syntax.It takes the first 8 characters of the commit SHA.
      - name: Show the SHA values 
        run: |
          echo "TAG = ${{env.TAG }}"
      - name: Login to Dockerhub 
        run: |
          echo "${{ secrets.PASSWORD }}" | docker login -u ${{secrets.USERNAME}} --password-stdin
      - name: Build and Tag 
        run: |
          docker build -t ${{ secrets.USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{env.TAG }} .
      - name: Push to Dockerhub 
        run: |
          docker push ${{ secrets.USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{env.TAG }}
      - name: Logout from Dockerhub 
        if: always()
        run: |
          docker logout 
# update helm repo with new image

  # ✅ Step 3 - Create Cloudflare DNS

  dns-job:
    needs: ci-job
    uses: ./.github/workflows/dns-cloudflare.yml  # ← import from file
    secrets:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
      SERVER_IP: ${{ secrets.SERVER_IP }}
    with:
      domain: "seang.shop"                         # ← pass domain as input

  cd-job: 
    needs: ci-job
    runs-on: ubuntu-latest 
    environment: HELM_ENV
    steps: 
      - name: Install yq command 
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
      - name: Add Commit SHA to TAG env 
        run: |
          echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
      
      # we clone the helm repo remporarily 
      - name: Clone argocd repo 
        run: | 
          git clone https://github.com/${{ env.HELM_REPO }} helm_repo 
      - name: Update Helm Chart 
        run: |
          cd helm_repo/${{ env.GITOPS_REPO }}
          echo "we Update repository username/imagename "

          yq -i "
            .image.repository = \"${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}\" |
            .image.tag = \"${{ env.TAG }}\" |
            .ingress.hosts[0].host = \"$FULL_DOMAIN\" |
            .ingress.tls[0].hosts[0] = \"$FULL_DOMAIN\" |
            .ingress.tls[0].secretName = \"$SUBDOMAIN-tls\"
          " values.yaml


          echo "Update image tag "
          yq -i ".image.tag=\"${{ env.TAG }}\"" values.yaml
          git config --global user.email "pengseangsim210@gmail.com"
          git config --global user.name "seang454"
          git add . 
          git commit -m "Update helm to use image ${{ env.TAG }}"
          
          git push https://${{ secrets.GIT_TOKEN }}@github.com/${{ env.HELM_REPO }}
      
      - name: Clean up 
        run: | 
          rm -rf helm_repo